name: Solve Model

on:
  push:
    branches:
      - test

jobs:
  sync-repository:
    runs-on: ubuntu-latest
    environment: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get New Optilogic Token
        id: get_token
        run: |
          token=$(python optilogic/get_token.py --username=${{ secrets.OPTILOGIC_USERNAME }} --password=${{ secrets.OPTILOGIC_PASSWORD }} -d)
          echo "::set-output name=optilogic_token::$token"
      -
        name: Optilogic Sync Job
        id: sync-repository
        env:
          optilogic_token: ${{ steps.get_token.outputs.optilogic_token }}
          optilogic_workspace: 'Ursa-Minor'
          optilogic_directory_path: 'My Models/optimization-ops/optilogic'
          optilogic_filename: 'sync_repo.py'
        run: |
          shaTag=$(git rev-parse --short "$GITHUB_SHA") && \
          job_key=$(python optilogic/create_job.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --directoryPath="${optilogic_directory_path}" --filename="$optilogic_filename" --jobTags="$shaTag,syncrepo" -d)
          echo "::set-output name=sync_job_key::$job_key"
          job_status=$(python optilogic/wait_for_job_completion.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --jobKey=$job_key -d)
          echo "Sync Job is $job_status"
  solve-test:
    runs-on: ubuntu-latest
    needs: sync-repository
    environment: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2 
      -
        name: Get New Optilogic Token
        id: get_token
        run: |
          token=$(python optilogic/get_token.py --username=${{ secrets.OPTILOGIC_USERNAME }} --password=${{ secrets.OPTILOGIC_PASSWORD }} -d)
          echo "::set-output name=optilogic_token::$token" 
      -
        name: Solve Model
        env:
          optilogic_token: ${{ steps.get_token.outputs.optilogic_token }}
          optilogic_workspace: 'Ursa-Minor'
          optilogic_directory_path: 'My Models/optimization-ops/src'
          optilogic_filename: 'solve.py'
          commandArgs: '--scenario=baseline'
        run: |
          shaTag=$(git rev-parse --short "$GITHUB_SHA") && \
          job_key=$(python optilogic/create_job.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --directoryPath="${optilogic_directory_path}" --filename="$optilogic_filename" --commandArgs="$commandArgs" --jobTags="$shaTag,solvetest" -d)
          echo "::set-output name=sync_job_key::$job_key"
          job_status=$(python optilogic/wait_for_job_completion.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --jobKey=$job_key -d)
          echo "Sync Job is $job_status"
  timetest:
    runs-on: ubuntu-latest
    needs: sync-repository
    environment: test
    strategy:
      matrix:
        timeout: [20, 21, 121, 300]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2 
      -
        name: Get New Optilogic Token
        id: get_token
        run: |
          token=$(python optilogic/get_token.py --username=${{ secrets.OPTILOGIC_USERNAME }} --password=${{ secrets.OPTILOGIC_PASSWORD }} -d)
          echo "::set-output name=optilogic_token::$token"
      -
        name: Solve Model
        env:
          optilogic_token: ${{ steps.get_token.outputs.optilogic_token }}
          optilogic_workspace: 'Ursa-Minor'
          optilogic_directory_path: 'My Models/optimization-ops/src'
          optilogic_filename: 'solve.py'
          commandArgs: '--scenario=baseline -tt'
          timeout: ${{ matrix.timeout }}
        run: |
          shaTag=$(git rev-parse --short "$GITHUB_SHA") && \
          job_key=$(python optilogic/create_job.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --directoryPath="${optilogic_directory_path}" --filename="$optilogic_filename" --commandArgs="$commandArgs" --timeout=$timeout --jobTags="$shaTag,timetest" -d)
          echo "::set-output name=sync_job_key::$job_key"
          job_status=$(python optilogic/wait_for_job_completion.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --jobKey=$job_key -d)
          echo "Sync Job is $job_status"
  oomtest:
    runs-on: ubuntu-latest
    needs: sync-repository
    environment: test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2 
      -
        name: Get New Optilogic Token
        id: get_token
        run: |
          token=$(python optilogic/get_token.py --username=${{ secrets.OPTILOGIC_USERNAME }} --password=${{ secrets.OPTILOGIC_PASSWORD }} -d)
          echo "::set-output name=optilogic_token::$token"
      -
        name: Solve Model
        env:
          optilogic_token: ${{ steps.get_token.outputs.optilogic_token }}
          optilogic_workspace: 'Ursa-Minor'
          optilogic_directory_path: 'My Models/optimization-ops/src'
          optilogic_filename: 'solve.py'
          commandArgs: '--scenario=baseline -oo'
        run: |
          shaTag=$(git rev-parse --short "$GITHUB_SHA") && \
          job_key=$(python optilogic/create_job.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --directoryPath="${optilogic_directory_path}" --filename="$optilogic_filename" --commandArgs="$commandArgs" --jobTags="$shaTag,oomtest" -d)
          echo "::set-output name=sync_job_key::$job_key"
          job_status=$(python optilogic/wait_for_job_completion.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --jobKey=$job_key -d)
          echo "Sync Job is $job_status"
  batchtest:
    runs-on: ubuntu-latest
    needs: sync-repository
    environment: test
    strategy:
      matrix:
        searchForMatches: ["True", "False"]
        jobify: ["True", "False"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2 
      -
        name: Get New Optilogic Token
        id: get_token
        run: |
          token=$(python optilogic/get_token.py --username=${{ secrets.OPTILOGIC_USERNAME }} --password=${{ secrets.OPTILOGIC_PASSWORD }} -d)
          echo "::set-output name=optilogic_token::$token"
      -
        name: Create Batch
        env:
          optilogic_token: ${{ steps.get_token.outputs.optilogic_token }}
          optilogic_workspace: 'Ursa-Minor'
          search: ${{ matrix.searchForMatches }}
          jobify: ${{ matrix.jobify }}
        run: |
          shaTag=$(git rev-parse --short "$GITHUB_SHA") && \
          job_keys=$(python optilogic/create_job_batch.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --searchForMatches="$search" --jobify="$jobify" --jobTags="$shaTag,batchtest,$search,$jobify" -d)
          all_job_status=$(python optilogic/wait_for_job_batch.py --apiKey=$optilogic_token --workspace=$optilogic_workspace --jobKeys=$job_keys -d)
          echo "Sync Job is $all_job_status"